### ISSUE TITLE
Suggestions and Package Errors

### ISSUE THREAD

**Issue by ariv797** [thevickypedia/Jarvis#9]
Instead of Jarvis continuously saying 'sir', both to a man and woman, he can differentiate using this package and speak to the user more effectively (by saying sir and maam):-
https://pypi.org/project/voice-analyzer

Also I am getting the following error while installing search-engine-parser package:-

ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly

Please help

PS can you please review the pull request I submitted #8

**Comment by thevickypedia** [comment]
@ariv797 Thanks for the suggestion and the PR
About the suggestions: I will work on it over the weekend or in early Feb
About the PR: I did not visit github before adding my commits on top it. I have some refactoring inlined, so I will add your changes to my commit and close the PR without merging it. That way it doesn't create any gray area or merge conflicts.
About the error you are seeing: I think I installed wheel through some other package in a different application which is why I am unable to replicate the issue. I will look into it and update the installs script file accordingly. In the mean time you can try to fix it by installing wheel separately and then try to install `search-engine-parser` either way, I will keep the issue open until I fix it or replicate the issue.

Once again thanks for suggestion and PR. Keep it coming :)

**Comment by thevickypedia** [comment]
@ariv797 I don't understand how the package works.
Google/pip doesn't allow me to install version 2.1.0 which the voice-analyzer package requires. It doesn't support the latest version 2.4.1 so I'm not sure if this package is even worth looking into. I think the repo no longer exists or the user has made it private to even check the read me.
I wouldn't be spending time on it, if you see any please feel free to raise a PR.

About the Package Error: Are you running a Windows?

**Comment by ariv797** [comment]
Sorry about the package (I think it requires Tenserflow 2.1). I will explore and research more about voice analyzing and will submit a PR of the same.

And yes, I am a Windows user.

**Comment by ariv797** [comment]
Was there a problem with the screenshot feature?
If you are a MacOs user, it is mentioned in PyAutoGUI's github repo that you need to install rubicon-objc package.
Repo - https://github.com/asweigart/pyautogui
Package - https://pypi.org/project/rubicon-objc/

**Comment by ariv797** [comment]
I have submitted two PRs, please review them.

**Comment by thevickypedia** [comment]
Windows requires updated C++ and VS to be installed (latest version)
If you print a trace, it should show you even the link where you can download it from. I stopped using Windows for Jarvis as I ought to use libraries for each and every feature which is annoying. So if you can get the trace, I will look and let you know to figure out a way around it.
I did try the screenshot feature yet for 2 reasons:
1. I don't see much value in it, as mostly it will either be PyCharm or iTerm that will be up on the screen when Jarvis is running.
2. Even thought it may slightly provide value in the background, I'd solve it with a simple apple script or keyboard shortcuts.
